export enum TidslinjehendelseType {
    FØRSTEGANGSSØKNAD = 'FØRSTEGANGSSØKNAD',
    FØRSTEGANGSSØKNAD_NY = 'FØRSTEGANGSSØKNAD_NY',
    ETTERSENDING = 'ETTERSENDING',
    ENDRINGSSØKNAD = 'ENDRINGSSØKNAD',
    INNTEKTSMELDING = 'INNTEKTSMELDING',
    VEDTAK = 'VEDTAK',
    VEDTAK_FØRSTEGANG = 'VEDTAK_FØRSTEGANG',
    VEDTAK_ENDRING = 'VEDTAK_ENDRING',
    VEDTAK_TILBAKEKREVING = 'VEDTAK_TILBAKEKREVING',
    VENTER_INNTEKTSMELDING = 'VENTER_INNTEKTSMELDING',
    UTGÅENDE_INNHENT_OPPLYSNINGER = 'UTGÅENDE_INNHENT_OPPLYSNINGER',
}
