export enum TidslinjehendelseType {
    FØRSTEGANGSSØKNAD = 'FØRSTEGANGSSØKNAD',
    ENDRINGSSØKNAD = 'ENDRINGSSØKNAD',
    INNTEKTSMELDING = 'INNTEKTSMELDING',
    VEDTAK_FØRSTEGANG = 'VEDTAK_FØRSTEGANG',
    VEDTAK_ENDRING = 'VEDTAK_ENDRING',
    VEDTAK_TILBAKEKREVING = 'VEDTAK_TILBAKEKREVING',
    VENTER_INNTEKTSMELDING = 'VENTER_INNTEKTSMELDING',
    ETTERSENDING = 'ETTERSENDING',
}
