export default interface Behandling {
    opprettetTidspunkt: string;
    endretTidspunkt: string;
    behandlendeEnhet: string;
    behandlendeEnhetNavn: string;
    status: BehandlingStatus;
    tema: BehandlingTema;
    type: BehandlingType;
    årsak: BehandlingÅrsak | null;
    behandlingResultat: BehandlingResultatType;
    inntektsmeldinger: string[];
}

export enum BehandlingResultatType {
    IKKE_FASTSATT = 'IKKE_FASTSATT',
    INNVILGET = 'INNVILGET',
    AVSLÅTT = 'AVSLÅTT',
    OPPHØR = 'OPPHØR',
    HENLAGT_SØKNAD_TRUKKET = 'HENLAGT_SØKNAD_TRUKKET',
    HENLAGT_FEILOPPRETTET = 'HENLAGT_FEILOPPRETTET',
    HENLAGT_BRUKER_DØD = 'HENLAGT_BRUKER_DØD',
    MERGET_OG_HENLAGT = 'MERGET_OG_HENLAGT',
    HENLAGT_SØKNAD_MANGLER = 'HENLAGT_SØKNAD_MANGLER',

    KLAGE_AVVIST = 'KLAGE_AVVIST',
    KLAGE_MEDHOLD = 'KLAGE_MEDHOLD',
    KLAGE_YTELSESVEDTAK_OPPHEVET = 'KLAGE_YTELSESVEDTAK_OPPHEVET',
    KLAGE_YTELSESVEDTAK_STADFESTET = 'KLAGE_YTELSESVEDTAK_STADFESTET',
    HENLAGT_KLAGE_TRUKKET = 'HENLAGT_KLAGE_TRUKKET',

    INNSYN_INNVILGET = 'INNSYN_INNVILGET',
    INNSYN_DELVIS_INNVILGET = 'INNSYN_DELVIS_INNVILGET',
    INNSYN_AVVIST = 'INNSYN_AVVIST',

    FORELDREPENGER_ENDRET = 'FORELDREPENGER_ENDRET',
}

export enum BehandlingStatus {
    OPPRETTET = 'OPPRE',
    UTREDES = 'UTRED',
    FATTER_VEDTAK = 'FVED',
    IVERKSETTER_VEDTAK = 'IVED',
    AVSLUTTET = 'AVSLU',
}

export enum BehandlingÅrsak {
    ANNET = 'RE-ANNET',
    BEREGNINGSGRUNNLAG = 'RE-BER-GRUN',
    BERØRT_BEHANDLING = 'BERØRT-BEHANDLING',
    DØD = 'RE-DØD',
    ENDRET_INNTEKTSMELDING = 'RE-END-INNTEKTSMELD',
    ENDRING_BEREGNINGSGRUNNLAG = 'RE-ENDR-BER-GRUN',
    ENDRING_FRA_BRUKER = 'RE-END-FRA-BRUKER',
    ETTER_KLAGE = 'ETTER_KLAGE',
    FEIL_ELLER_ENDRET_FAKTA = 'RE-FEFAKTA',
    FEIL_LOVANVENDELSE = 'RE-LOV',
    FEIL_REGELVERKSFORSTÅELSE = 'RE-RGLF',
    FORDELING_STØNADSPERIODE = 'RE-FRDLING',
    HENDELSE_FØDSEL = 'RE-HENDELSE-FØDSEL',
    INNTEKT = 'RE-INNTK',
    KLAGE = 'RE-KLAG',
    KØET_BEHANDLING = 'KØET_BEHANDLING',
    MANGLENDE_FØDSEL = 'RE-MF',
    MANGLENDE_FØDSEL_TERMIN = 'RE-MFIP',
    MEDLEMSKAP = 'RE-MDL',
    OPPTJENING = 'RE-OPTJ',
    PROSESSURELL_FEIL = 'RE-PRSSL',
    REGISTER_OPPLYSNING = 'RE-REGISTEROPPL',
    RELASJON_TIL_BARNET = 'RE-SRTB',
    SØKNADSFRIST = 'RE-FRIST',
    TILSTØTENDE_YTELSE_INNVILGET = 'RE-TILST-YT-INNVIL',
    TILSTØTENDE_YTELSE_OPPHØRT = 'RE-TILST-YT-OPPH',
    ULIKT_ANTALL_BARN = 'RE-AVAB',
    YTELSE = 'RE-YTELSE',
}

export enum BehandlingType {
    FORELDREPENGESØKNAD = 'FP',
    ENGANGSSØNAD = 'ES',
    ENDRINGSSØKNAD = 'ENDRING',
    SVANGERSKAPSPENGESØKNAD = 'SVP',
}

export enum BehandlingTema {
    ENGANGSTØNAD = 'ENGST',
    ENGANGSTØNAD_FØDSEL = 'ENGST_FODS',
    ENGANGSTØNAD_ADOPSJON = 'ENGST_ADOP',
    FORELDREPENGER = 'FORP',
    FORELDREPENGER_ADOPSJON = 'FORP_ADOP',
    FORELDREPENGER_FØDSEL = 'FORP_FODS',
    SVANGERSKAPSPENGER = 'SVP',
    UDEFINERT = '-',
}
